parameters:
    zeta_search.session.class: ezcSearchSession
    zeta_search.manager.embedded.class: ezcSearchEmbeddedManager
    zeta_search.manager.xml.class: ezcSearchXmlManager
    zeta_search.handler.solr.class: ezcSearchSolrHandler
    zeta_search.handler.zendlucene.class: ezcSearchZendLuceneHandler

services:
    zeta_search.listener:
        class: F5\Bundle\ZetaSearchBundle\EventListener\EzcSearchListener
        tags:
            - {name: doctrine.event_listener, event: preUpdate}
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: preDelete}
        arguments: [@zeta_search.session]

    zeta_search.session:
        class: %zeta_search.session.class%
        arguments: [@zeta_search.handler, @zeta_search.manager]

    zeta_search.manager.embedded:
        class: %zeta_search.manager.embedded.class%

    zeta_search.manager.xml:
        class: %zeta_search.manager.xml.class%
        arguments: [%zeta_search.xml-manager.path%]

    zeta_search.handler.solr:
        class: %zeta_search.handler.solr.class%
        arguments: [%zeta_search.solr.host%,%zeta_search.solr.port%,%zeta_search.solr.location%]

    zeta_search.handler.zendlucene:
        class: %zeta_search.handler.zendlucene.class%
        arguments: [%zeta_search.zendlucene.data_dir%]