parameters:
    zeta.search.session.class: ezcSearchSession
    zeta.search.manager.embedded.class: ezcSearchEmbeddedManager
    zeta.search.manager.xml.class: ezcSearchXmlManager
    zeta.search.handler.solr.class: ezcSearchSolrHandler
    zeta.search.handler.zendlucene.class: ezcSearchZendLuceneHandler

services:
    zeta.search.listener:
        class: F5\Bundle\ZetaBundle\EventListener\EzcSearchListener
        tags:
            - {name: doctrine.event_listener, event: preUpdate}
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: preDelete}
        arguments: [@zeta.search.session]

    zeta.search.session:
        class: %zeta.search.session.class%
        arguments: [@zeta.search.handler, @zeta.search.manager]

    zeta.search.manager.embedded:
        class: %zeta.search.manager.embedded.class%

    zeta.search.manager.xml:
        class: %zeta.search.manager.xml.class%
        arguments: [%zeta.search.xml-manager.path%]

    zeta.search.handler.solr:
        class: %zeta.search.handler.solr.class%
        arguments: [%zeta.search.solr.host%,%zeta.search.solr.port%,%zeta.search.solr.location%]

    zeta.search.handler.zendlucene:
        class: %zeta.search.handler.zendlucene.class%
        arguments: [%zeta.search.zendlucene.data_dir%]